# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visual.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 601)
        MainWindow.setMinimumSize(QtCore.QSize(801, 601))
        MainWindow.setMaximumSize(QtCore.QSize(801, 601))
        MainWindow.setStyleSheet("background-color: #242d44")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-2, 0, 841, 601))
        self.tabWidget.setMinimumSize(QtCore.QSize(801, 0))
        self.tabWidget.setStyleSheet("background-color: #242d44")
        self.tabWidget.setObjectName("tabWidget")
        self.profile_tab = QtWidgets.QWidget()
        self.profile_tab.setStyleSheet("")
        self.profile_tab.setObjectName("profile_tab")
        self.update_information_button = QtWidgets.QPushButton(self.profile_tab)
        self.update_information_button.setGeometry(QtCore.QRect(631, 0, 161, 31))
        self.update_information_button.setStyleSheet("color: white; background-color: grey")
        self.update_information_button.setObjectName("update_information_button")
        self.choose_acc_listWidget = QtWidgets.QListWidget(self.profile_tab)
        self.choose_acc_listWidget.setGeometry(QtCore.QRect(0, 0, 256, 100))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.choose_acc_listWidget.setFont(font)
        self.choose_acc_listWidget.setStyleSheet("color: white")
        self.choose_acc_listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.choose_acc_listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.choose_acc_listWidget.setObjectName("choose_acc_listWidget")
        self.current_rank_text_label = QtWidgets.QLabel(self.profile_tab)
        self.current_rank_text_label.setGeometry(QtCore.QRect(154, 185, 220, 39))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.current_rank_text_label.setFont(font)
        self.current_rank_text_label.setStyleSheet("color: #9daac8")
        self.current_rank_text_label.setObjectName("current_rank_text_label")
        self.current_rank_label = QtWidgets.QLabel(self.profile_tab)
        self.current_rank_label.setGeometry(QtCore.QRect(182, 154, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.current_rank_label.setFont(font)
        self.current_rank_label.setStyleSheet("color: white")
        self.current_rank_label.setAlignment(QtCore.Qt.AlignCenter)
        self.current_rank_label.setObjectName("current_rank_label")
        self.level_label = QtWidgets.QLabel(self.profile_tab)
        self.level_label.setGeometry(QtCore.QRect(451, 186, 129, 39))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.level_label.setFont(font)
        self.level_label.setStyleSheet("color: #9daac8")
        self.level_label.setAlignment(QtCore.Qt.AlignCenter)
        self.level_label.setObjectName("level_label")
        self.current_level_label = QtWidgets.QLabel(self.profile_tab)
        self.current_level_label.setGeometry(QtCore.QRect(456, 160, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.current_level_label.setFont(font)
        self.current_level_label.setStyleSheet("color: white")
        self.current_level_label.setAlignment(QtCore.Qt.AlignCenter)
        self.current_level_label.setObjectName("current_level_label")
        self.battle_tag_label = QtWidgets.QLabel(self.profile_tab)
        self.battle_tag_label.setGeometry(QtCore.QRect(410, 50, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.battle_tag_label.setFont(font)
        self.battle_tag_label.setStyleSheet("color: #9daac8")
        self.battle_tag_label.setObjectName("battle_tag_label")
        self.reputation_level_label = QtWidgets.QLabel(self.profile_tab)
        self.reputation_level_label.setGeometry(QtCore.QRect(128, 273, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.reputation_level_label.setFont(font)
        self.reputation_level_label.setStyleSheet("color: #9daac8")
        self.reputation_level_label.setObjectName("reputation_level_label")
        self.current_reputation_label = QtWidgets.QLabel(self.profile_tab)
        self.current_reputation_label.setGeometry(QtCore.QRect(198, 245, 50, 40))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.current_reputation_label.setFont(font)
        self.current_reputation_label.setStyleSheet("color: white")
        self.current_reputation_label.setAlignment(QtCore.Qt.AlignCenter)
        self.current_reputation_label.setObjectName("current_reputation_label")
        self.timeinseason_text_label = QtWidgets.QLabel(self.profile_tab)
        self.timeinseason_text_label.setGeometry(QtCore.QRect(408, 279, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.timeinseason_text_label.setFont(font)
        self.timeinseason_text_label.setStyleSheet("color: #9daac8")
        self.timeinseason_text_label.setObjectName("timeinseason_text_label")
        self.avatar_label = QtWidgets.QLabel(self.profile_tab)
        self.avatar_label.setGeometry(QtCore.QRect(261, 20, 140, 120))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.avatar_label.setFont(font)
        self.avatar_label.setStyleSheet("color: white")
        self.avatar_label.setText("")
        self.avatar_label.setObjectName("avatar_label")
        self.current_hours_played_inrank_label = QtWidgets.QLabel(self.profile_tab)
        self.current_hours_played_inrank_label.setGeometry(QtCore.QRect(476, 250, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.current_hours_played_inrank_label.setFont(font)
        self.current_hours_played_inrank_label.setStyleSheet("color: white")
        self.current_hours_played_inrank_label.setAlignment(QtCore.Qt.AlignCenter)
        self.current_hours_played_inrank_label.setObjectName("current_hours_played_inrank_label")
        self.wins_text_label = QtWidgets.QLabel(self.profile_tab)
        self.wins_text_label.setGeometry(QtCore.QRect(73, 380, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.wins_text_label.setFont(font)
        self.wins_text_label.setStyleSheet("color: #9daac8")
        self.wins_text_label.setObjectName("wins_text_label")
        self.games_lost_text_label = QtWidgets.QLabel(self.profile_tab)
        self.games_lost_text_label.setGeometry(QtCore.QRect(73, 415, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.games_lost_text_label.setFont(font)
        self.games_lost_text_label.setStyleSheet("color: #9daac8")
        self.games_lost_text_label.setObjectName("games_lost_text_label")
        self.games_tied_text_label = QtWidgets.QLabel(self.profile_tab)
        self.games_tied_text_label.setGeometry(QtCore.QRect(73, 455, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.games_tied_text_label.setFont(font)
        self.games_tied_text_label.setStyleSheet("color: #9daac8")
        self.games_tied_text_label.setObjectName("games_tied_text_label")
        self.current_games_won_label = QtWidgets.QLabel(self.profile_tab)
        self.current_games_won_label.setGeometry(QtCore.QRect(230, 381, 95, 30))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.current_games_won_label.setFont(font)
        self.current_games_won_label.setStyleSheet("color: white")
        self.current_games_won_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.current_games_won_label.setObjectName("current_games_won_label")
        self.current_games_lost_label = QtWidgets.QLabel(self.profile_tab)
        self.current_games_lost_label.setGeometry(QtCore.QRect(230, 410, 85, 40))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.current_games_lost_label.setFont(font)
        self.current_games_lost_label.setStyleSheet("color: white")
        self.current_games_lost_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.current_games_lost_label.setObjectName("current_games_lost_label")
        self.current_games_tied_label = QtWidgets.QLabel(self.profile_tab)
        self.current_games_tied_label.setGeometry(QtCore.QRect(230, 450, 80, 40))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.current_games_tied_label.setFont(font)
        self.current_games_tied_label.setStyleSheet("color: white")
        self.current_games_tied_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.current_games_tied_label.setObjectName("current_games_tied_label")
        self.winrate_text_label = QtWidgets.QLabel(self.profile_tab)
        self.winrate_text_label.setGeometry(QtCore.QRect(71, 327, 130, 40))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.winrate_text_label.setFont(font)
        self.winrate_text_label.setStyleSheet("color: #9daac8")
        self.winrate_text_label.setObjectName("winrate_text_label")
        self.current_winrate_acc_label = QtWidgets.QLabel(self.profile_tab)
        self.current_winrate_acc_label.setGeometry(QtCore.QRect(230, 328, 151, 40))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.current_winrate_acc_label.setFont(font)
        self.current_winrate_acc_label.setStyleSheet("color: white")
        self.current_winrate_acc_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.current_winrate_acc_label.setObjectName("current_winrate_acc_label")
        self.last_activity_label = QtWidgets.QLabel(self.profile_tab)
        self.last_activity_label.setGeometry(QtCore.QRect(390, 325, 340, 40))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.last_activity_label.setFont(font)
        self.last_activity_label.setStyleSheet("color: #9daac8")
        self.last_activity_label.setObjectName("last_activity_label")
        self.change_games_won_label = QtWidgets.QLabel(self.profile_tab)
        self.change_games_won_label.setGeometry(QtCore.QRect(550, 411, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.change_games_won_label.setFont(font)
        self.change_games_won_label.setStyleSheet("color: white")
        self.change_games_won_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.change_games_won_label.setObjectName("change_games_won_label")
        self.games_lost_change_text_label = QtWidgets.QLabel(self.profile_tab)
        self.games_lost_change_text_label.setGeometry(QtCore.QRect(393, 445, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.games_lost_change_text_label.setFont(font)
        self.games_lost_change_text_label.setStyleSheet("color: #9daac8")
        self.games_lost_change_text_label.setObjectName("games_lost_change_text_label")
        self.wins_change_text_label = QtWidgets.QLabel(self.profile_tab)
        self.wins_change_text_label.setGeometry(QtCore.QRect(393, 410, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.wins_change_text_label.setFont(font)
        self.wins_change_text_label.setStyleSheet("color: #9daac8")
        self.wins_change_text_label.setObjectName("wins_change_text_label")
        self.games_tied_change_text_label = QtWidgets.QLabel(self.profile_tab)
        self.games_tied_change_text_label.setGeometry(QtCore.QRect(393, 485, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.games_tied_change_text_label.setFont(font)
        self.games_tied_change_text_label.setStyleSheet("color: #9daac8")
        self.games_tied_change_text_label.setObjectName("games_tied_change_text_label")
        self.change_games_lost_label = QtWidgets.QLabel(self.profile_tab)
        self.change_games_lost_label.setGeometry(QtCore.QRect(550, 440, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.change_games_lost_label.setFont(font)
        self.change_games_lost_label.setStyleSheet("color: white")
        self.change_games_lost_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.change_games_lost_label.setObjectName("change_games_lost_label")
        self.change_games_tied_label = QtWidgets.QLabel(self.profile_tab)
        self.change_games_tied_label.setGeometry(QtCore.QRect(550, 480, 115, 40))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.change_games_tied_label.setFont(font)
        self.change_games_tied_label.setStyleSheet("color: white")
        self.change_games_tied_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.change_games_tied_label.setObjectName("change_games_tied_label")
        self.last_rank_change_text_label = QtWidgets.QLabel(self.profile_tab)
        self.last_rank_change_text_label.setGeometry(QtCore.QRect(393, 369, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.last_rank_change_text_label.setFont(font)
        self.last_rank_change_text_label.setStyleSheet("color: #9daac8")
        self.last_rank_change_text_label.setObjectName("last_rank_change_text_label")
        self.last_change_rank_label = QtWidgets.QLabel(self.profile_tab)
        self.last_change_rank_label.setGeometry(QtCore.QRect(550, 370, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.last_change_rank_label.setFont(font)
        self.last_change_rank_label.setStyleSheet("color: white")
        self.last_change_rank_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.last_change_rank_label.setObjectName("last_change_rank_label")
        self.rank_avatar_label = QtWidgets.QLabel(self.profile_tab)
        self.rank_avatar_label.setGeometry(QtCore.QRect(132, 149, 45, 45))
        self.rank_avatar_label.setText("")
        self.rank_avatar_label.setObjectName("rank_avatar_label")
        self.tabWidget.addTab(self.profile_tab, "")
        self.statistic_tab = QtWidgets.QWidget()
        self.statistic_tab.setObjectName("statistic_tab")
        self.most_eliminations_acc_text_lable = QtWidgets.QLabel(self.statistic_tab)
        self.most_eliminations_acc_text_lable.setGeometry(QtCore.QRect(23, 23, 180, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.most_eliminations_acc_text_lable.setFont(font)
        self.most_eliminations_acc_text_lable.setStyleSheet("color: #9daac8")
        self.most_eliminations_acc_text_lable.setObjectName("most_eliminations_acc_text_lable")
        self.total_eliminations_acc_text_lable = QtWidgets.QLabel(self.statistic_tab)
        self.total_eliminations_acc_text_lable.setGeometry(QtCore.QRect(24, 58, 80, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.total_eliminations_acc_text_lable.setFont(font)
        self.total_eliminations_acc_text_lable.setStyleSheet("color: #9daac8")
        self.total_eliminations_acc_text_lable.setObjectName("total_eliminations_acc_text_lable")
        self.most_elims_acc_label = QtWidgets.QLabel(self.statistic_tab)
        self.most_elims_acc_label.setGeometry(QtCore.QRect(240, 24, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.most_elims_acc_label.setFont(font)
        self.most_elims_acc_label.setStyleSheet("color: white")
        self.most_elims_acc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.most_elims_acc_label.setObjectName("most_elims_acc_label")
        self.total_elims_acc_label = QtWidgets.QLabel(self.statistic_tab)
        self.total_elims_acc_label.setGeometry(QtCore.QRect(240, 58, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.total_elims_acc_label.setFont(font)
        self.total_elims_acc_label.setStyleSheet("color: white")
        self.total_elims_acc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.total_elims_acc_label.setObjectName("total_elims_acc_label")
        self.most_final_blows_acc_text_label = QtWidgets.QLabel(self.statistic_tab)
        self.most_final_blows_acc_text_label.setGeometry(QtCore.QRect(444, 20, 190, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.most_final_blows_acc_text_label.setFont(font)
        self.most_final_blows_acc_text_label.setStyleSheet("color: #9daac8")
        self.most_final_blows_acc_text_label.setObjectName("most_final_blows_acc_text_label")
        self.total_final_blows_acc_text_label = QtWidgets.QLabel(self.statistic_tab)
        self.total_final_blows_acc_text_label.setGeometry(QtCore.QRect(444, 56, 130, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.total_final_blows_acc_text_label.setFont(font)
        self.total_final_blows_acc_text_label.setStyleSheet("color: #9daac8")
        self.total_final_blows_acc_text_label.setObjectName("total_final_blows_acc_text_label")
        self.most_final_blows_acc_label = QtWidgets.QLabel(self.statistic_tab)
        self.most_final_blows_acc_label.setGeometry(QtCore.QRect(651, 20, 130, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.most_final_blows_acc_label.setFont(font)
        self.most_final_blows_acc_label.setStyleSheet("color: white")
        self.most_final_blows_acc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.most_final_blows_acc_label.setObjectName("most_final_blows_acc_label")
        self.total_final_blows_acc_label = QtWidgets.QLabel(self.statistic_tab)
        self.total_final_blows_acc_label.setGeometry(QtCore.QRect(650, 57, 130, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.total_final_blows_acc_label.setFont(font)
        self.total_final_blows_acc_label.setStyleSheet("color: white")
        self.total_final_blows_acc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.total_final_blows_acc_label.setObjectName("total_final_blows_acc_label")
        self.most_obj_elims_acc_text_label = QtWidgets.QLabel(self.statistic_tab)
        self.most_obj_elims_acc_text_label.setGeometry(QtCore.QRect(22, 130, 220, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.most_obj_elims_acc_text_label.setFont(font)
        self.most_obj_elims_acc_text_label.setStyleSheet("color: #9daac8")
        self.most_obj_elims_acc_text_label.setObjectName("most_obj_elims_acc_text_label")
        self.total_obj_elims_acc_text_label = QtWidgets.QLabel(self.statistic_tab)
        self.total_obj_elims_acc_text_label.setGeometry(QtCore.QRect(22, 168, 220, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.total_obj_elims_acc_text_label.setFont(font)
        self.total_obj_elims_acc_text_label.setStyleSheet("color: #9daac8")
        self.total_obj_elims_acc_text_label.setObjectName("total_obj_elims_acc_text_label")
        self.most_obj_elims_acc_label = QtWidgets.QLabel(self.statistic_tab)
        self.most_obj_elims_acc_label.setGeometry(QtCore.QRect(257, 130, 120, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.most_obj_elims_acc_label.setFont(font)
        self.most_obj_elims_acc_label.setStyleSheet("color: white")
        self.most_obj_elims_acc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.most_obj_elims_acc_label.setObjectName("most_obj_elims_acc_label")
        self.total_obj_elims_acc_label = QtWidgets.QLabel(self.statistic_tab)
        self.total_obj_elims_acc_label.setGeometry(QtCore.QRect(257, 169, 120, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.total_obj_elims_acc_label.setFont(font)
        self.total_obj_elims_acc_label.setStyleSheet("color: white")
        self.total_obj_elims_acc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.total_obj_elims_acc_label.setObjectName("total_obj_elims_acc_label")
        self.most_obj_time_acc_text_label = QtWidgets.QLabel(self.statistic_tab)
        self.most_obj_time_acc_text_label.setGeometry(QtCore.QRect(439, 128, 210, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.most_obj_time_acc_text_label.setFont(font)
        self.most_obj_time_acc_text_label.setStyleSheet("color: #9daac8")
        self.most_obj_time_acc_text_label.setObjectName("most_obj_time_acc_text_label")
        self.total_obj_time_acc_text_label = QtWidgets.QLabel(self.statistic_tab)
        self.total_obj_time_acc_text_label.setGeometry(QtCore.QRect(439, 164, 210, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.total_obj_time_acc_text_label.setFont(font)
        self.total_obj_time_acc_text_label.setStyleSheet("color: #9daac8")
        self.total_obj_time_acc_text_label.setObjectName("total_obj_time_acc_text_label")
        self.most_obj_time_acc_label = QtWidgets.QLabel(self.statistic_tab)
        self.most_obj_time_acc_label.setGeometry(QtCore.QRect(660, 127, 110, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.most_obj_time_acc_label.setFont(font)
        self.most_obj_time_acc_label.setStyleSheet("color: white")
        self.most_obj_time_acc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.most_obj_time_acc_label.setObjectName("most_obj_time_acc_label")
        self.total_obj_time_acc_label = QtWidgets.QLabel(self.statistic_tab)
        self.total_obj_time_acc_label.setGeometry(QtCore.QRect(660, 165, 110, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.total_obj_time_acc_label.setFont(font)
        self.total_obj_time_acc_label.setStyleSheet("color: white")
        self.total_obj_time_acc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.total_obj_time_acc_label.setObjectName("total_obj_time_acc_label")
        self.most_heroes_dmg_acc_text_label = QtWidgets.QLabel(self.statistic_tab)
        self.most_heroes_dmg_acc_text_label.setGeometry(QtCore.QRect(440, 260, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.most_heroes_dmg_acc_text_label.setFont(font)
        self.most_heroes_dmg_acc_text_label.setStyleSheet("color: #9daac8")
        self.most_heroes_dmg_acc_text_label.setObjectName("most_heroes_dmg_acc_text_label")
        self.total_heroes_dmg_acc_text_label = QtWidgets.QLabel(self.statistic_tab)
        self.total_heroes_dmg_acc_text_label.setGeometry(QtCore.QRect(440, 298, 180, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.total_heroes_dmg_acc_text_label.setFont(font)
        self.total_heroes_dmg_acc_text_label.setStyleSheet("color: #9daac8")
        self.total_heroes_dmg_acc_text_label.setObjectName("total_heroes_dmg_acc_text_label")
        self.most_heroes_dmg_acc_label = QtWidgets.QLabel(self.statistic_tab)
        self.most_heroes_dmg_acc_label.setGeometry(QtCore.QRect(650, 260, 130, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.most_heroes_dmg_acc_label.setFont(font)
        self.most_heroes_dmg_acc_label.setStyleSheet("color: white")
        self.most_heroes_dmg_acc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.most_heroes_dmg_acc_label.setObjectName("most_heroes_dmg_acc_label")
        self.total_heroes_dmg_acc_label = QtWidgets.QLabel(self.statistic_tab)
        self.total_heroes_dmg_acc_label.setGeometry(QtCore.QRect(650, 298, 130, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.total_heroes_dmg_acc_label.setFont(font)
        self.total_heroes_dmg_acc_label.setStyleSheet("color: white")
        self.total_heroes_dmg_acc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.total_heroes_dmg_acc_label.setObjectName("total_heroes_dmg_acc_label")
        self.most_healing_acc_text_label = QtWidgets.QLabel(self.statistic_tab)
        self.most_healing_acc_text_label.setGeometry(QtCore.QRect(440, 400, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.most_healing_acc_text_label.setFont(font)
        self.most_healing_acc_text_label.setStyleSheet("color: #9daac8")
        self.most_healing_acc_text_label.setObjectName("most_healing_acc_text_label")
        self.total_healing_acc_text_label = QtWidgets.QLabel(self.statistic_tab)
        self.total_healing_acc_text_label.setGeometry(QtCore.QRect(440, 441, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.total_healing_acc_text_label.setFont(font)
        self.total_healing_acc_text_label.setStyleSheet("color: #9daac8")
        self.total_healing_acc_text_label.setObjectName("total_healing_acc_text_label")
        self.most_healing_acc_label = QtWidgets.QLabel(self.statistic_tab)
        self.most_healing_acc_label.setGeometry(QtCore.QRect(656, 400, 120, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.most_healing_acc_label.setFont(font)
        self.most_healing_acc_label.setStyleSheet("color: white")
        self.most_healing_acc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.most_healing_acc_label.setObjectName("most_healing_acc_label")
        self.total_healing_acc_label = QtWidgets.QLabel(self.statistic_tab)
        self.total_healing_acc_label.setGeometry(QtCore.QRect(656, 441, 120, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.total_healing_acc_label.setFont(font)
        self.total_healing_acc_label.setStyleSheet("color: white")
        self.total_healing_acc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.total_healing_acc_label.setObjectName("total_healing_acc_label")
        self.most_fire_time_acc_text_label = QtWidgets.QLabel(self.statistic_tab)
        self.most_fire_time_acc_text_label.setGeometry(QtCore.QRect(27, 259, 220, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.most_fire_time_acc_text_label.setFont(font)
        self.most_fire_time_acc_text_label.setStyleSheet("color: #9daac8")
        self.most_fire_time_acc_text_label.setObjectName("most_fire_time_acc_text_label")
        self.total_fire_time_acc_text_label = QtWidgets.QLabel(self.statistic_tab)
        self.total_fire_time_acc_text_label.setGeometry(QtCore.QRect(27, 297, 160, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.total_fire_time_acc_text_label.setFont(font)
        self.total_fire_time_acc_text_label.setStyleSheet("color: #9daac8")
        self.total_fire_time_acc_text_label.setObjectName("total_fire_time_acc_text_label")
        self.most_fire_time_acc_label = QtWidgets.QLabel(self.statistic_tab)
        self.most_fire_time_acc_label.setGeometry(QtCore.QRect(251, 259, 130, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.most_fire_time_acc_label.setFont(font)
        self.most_fire_time_acc_label.setStyleSheet("color: white")
        self.most_fire_time_acc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.most_fire_time_acc_label.setObjectName("most_fire_time_acc_label")
        self.total_fire_time_acc_label = QtWidgets.QLabel(self.statistic_tab)
        self.total_fire_time_acc_label.setGeometry(QtCore.QRect(251, 298, 130, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.total_fire_time_acc_label.setFont(font)
        self.total_fire_time_acc_label.setStyleSheet("color: white")
        self.total_fire_time_acc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.total_fire_time_acc_label.setObjectName("total_fire_time_acc_label")
        self.most_solo_elims_acc_text_label = QtWidgets.QLabel(self.statistic_tab)
        self.most_solo_elims_acc_text_label.setGeometry(QtCore.QRect(30, 400, 220, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.most_solo_elims_acc_text_label.setFont(font)
        self.most_solo_elims_acc_text_label.setStyleSheet("color: #9daac8")
        self.most_solo_elims_acc_text_label.setObjectName("most_solo_elims_acc_text_label")
        self.total_solo_elims_acc_text_label = QtWidgets.QLabel(self.statistic_tab)
        self.total_solo_elims_acc_text_label.setGeometry(QtCore.QRect(30, 438, 220, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.total_solo_elims_acc_text_label.setFont(font)
        self.total_solo_elims_acc_text_label.setStyleSheet("color: #9daac8")
        self.total_solo_elims_acc_text_label.setObjectName("total_solo_elims_acc_text_label")
        self.most_solo_elims_acc_label = QtWidgets.QLabel(self.statistic_tab)
        self.most_solo_elims_acc_label.setGeometry(QtCore.QRect(260, 400, 110, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.most_solo_elims_acc_label.setFont(font)
        self.most_solo_elims_acc_label.setStyleSheet("color: white")
        self.most_solo_elims_acc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.most_solo_elims_acc_label.setObjectName("most_solo_elims_acc_label")
        self.total_solo_elims_acc_label = QtWidgets.QLabel(self.statistic_tab)
        self.total_solo_elims_acc_label.setGeometry(QtCore.QRect(260, 438, 110, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.total_solo_elims_acc_label.setFont(font)
        self.total_solo_elims_acc_label.setStyleSheet("color: white")
        self.total_solo_elims_acc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.total_solo_elims_acc_label.setObjectName("total_solo_elims_acc_label")
        self.tabWidget.addTab(self.statistic_tab, "")
        self.heroes_tab = QtWidgets.QWidget()
        self.heroes_tab.setObjectName("heroes_tab")
        self.avg_elims_hero_text_label = QtWidgets.QLabel(self.heroes_tab)
        self.avg_elims_hero_text_label.setGeometry(QtCore.QRect(202, 20, 170, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.avg_elims_hero_text_label.setFont(font)
        self.avg_elims_hero_text_label.setStyleSheet("color: #9daac8")
        self.avg_elims_hero_text_label.setObjectName("avg_elims_hero_text_label")
        self.avg_elims_hero_label = QtWidgets.QLabel(self.heroes_tab)
        self.avg_elims_hero_label.setGeometry(QtCore.QRect(400, 20, 110, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.avg_elims_hero_label.setFont(font)
        self.avg_elims_hero_label.setStyleSheet("color: white")
        self.avg_elims_hero_label.setAlignment(QtCore.Qt.AlignCenter)
        self.avg_elims_hero_label.setObjectName("avg_elims_hero_label")
        self.avg_obj_elims_hero_text_label = QtWidgets.QLabel(self.heroes_tab)
        self.avg_obj_elims_hero_text_label.setGeometry(QtCore.QRect(519, 15, 220, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.avg_obj_elims_hero_text_label.setFont(font)
        self.avg_obj_elims_hero_text_label.setStyleSheet("color: #9daac8")
        self.avg_obj_elims_hero_text_label.setObjectName("avg_obj_elims_hero_text_label")
        self.avg_obj_elims_hero_label = QtWidgets.QLabel(self.heroes_tab)
        self.avg_obj_elims_hero_label.setGeometry(QtCore.QRect(724, 15, 60, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.avg_obj_elims_hero_label.setFont(font)
        self.avg_obj_elims_hero_label.setStyleSheet("color: white")
        self.avg_obj_elims_hero_label.setAlignment(QtCore.Qt.AlignCenter)
        self.avg_obj_elims_hero_label.setObjectName("avg_obj_elims_hero_label")
        self.avg_damage_done_hero_text_label = QtWidgets.QLabel(self.heroes_tab)
        self.avg_damage_done_hero_text_label.setGeometry(QtCore.QRect(202, 60, 170, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.avg_damage_done_hero_text_label.setFont(font)
        self.avg_damage_done_hero_text_label.setStyleSheet("color: #9daac8")
        self.avg_damage_done_hero_text_label.setObjectName("avg_damage_done_hero_text_label")
        self.avg_damage_done_hero_label = QtWidgets.QLabel(self.heroes_tab)
        self.avg_damage_done_hero_label.setGeometry(QtCore.QRect(400, 60, 110, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.avg_damage_done_hero_label.setFont(font)
        self.avg_damage_done_hero_label.setStyleSheet("color: white")
        self.avg_damage_done_hero_label.setAlignment(QtCore.Qt.AlignCenter)
        self.avg_damage_done_hero_label.setObjectName("avg_damage_done_hero_label")
        self.abg_deaths_hero_text_label = QtWidgets.QLabel(self.heroes_tab)
        self.abg_deaths_hero_text_label.setGeometry(QtCore.QRect(520, 65, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.abg_deaths_hero_text_label.setFont(font)
        self.abg_deaths_hero_text_label.setStyleSheet("color: #9daac8")
        self.abg_deaths_hero_text_label.setObjectName("abg_deaths_hero_text_label")
        self.avg_deaths_hero_label = QtWidgets.QLabel(self.heroes_tab)
        self.avg_deaths_hero_label.setGeometry(QtCore.QRect(723, 67, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.avg_deaths_hero_label.setFont(font)
        self.avg_deaths_hero_label.setStyleSheet("color: white")
        self.avg_deaths_hero_label.setAlignment(QtCore.Qt.AlignCenter)
        self.avg_deaths_hero_label.setObjectName("avg_deaths_hero_label")
        self.avg_healing_done_hero_text_label = QtWidgets.QLabel(self.heroes_tab)
        self.avg_healing_done_hero_text_label.setGeometry(QtCore.QRect(200, 110, 180, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.avg_healing_done_hero_text_label.setFont(font)
        self.avg_healing_done_hero_text_label.setStyleSheet("color: #9daac8")
        self.avg_healing_done_hero_text_label.setObjectName("avg_healing_done_hero_text_label")
        self.avg_healing_done_hero_label = QtWidgets.QLabel(self.heroes_tab)
        self.avg_healing_done_hero_label.setGeometry(QtCore.QRect(390, 110, 130, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.avg_healing_done_hero_label.setFont(font)
        self.avg_healing_done_hero_label.setStyleSheet("color: white")
        self.avg_healing_done_hero_label.setAlignment(QtCore.Qt.AlignCenter)
        self.avg_healing_done_hero_label.setObjectName("avg_healing_done_hero_label")
        self.time_played_hero_text_label = QtWidgets.QLabel(self.heroes_tab)
        self.time_played_hero_text_label.setGeometry(QtCore.QRect(519, 115, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.time_played_hero_text_label.setFont(font)
        self.time_played_hero_text_label.setStyleSheet("color: #9daac8")
        self.time_played_hero_text_label.setObjectName("time_played_hero_text_label")
        self.time_played_hero_label = QtWidgets.QLabel(self.heroes_tab)
        self.time_played_hero_label.setGeometry(QtCore.QRect(719, 115, 70, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.time_played_hero_label.setFont(font)
        self.time_played_hero_label.setStyleSheet("color: white")
        self.time_played_hero_label.setAlignment(QtCore.Qt.AlignCenter)
        self.time_played_hero_label.setObjectName("time_played_hero_label")
        self.winrate_hero_text_label = QtWidgets.QLabel(self.heroes_tab)
        self.winrate_hero_text_label.setGeometry(QtCore.QRect(200, 160, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.winrate_hero_text_label.setFont(font)
        self.winrate_hero_text_label.setStyleSheet("color: #9daac8")
        self.winrate_hero_text_label.setObjectName("winrate_hero_text_label")
        self.winrate_hero_label = QtWidgets.QLabel(self.heroes_tab)
        self.winrate_hero_label.setGeometry(QtCore.QRect(410, 152, 90, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.winrate_hero_label.setFont(font)
        self.winrate_hero_label.setStyleSheet("color: white")
        self.winrate_hero_label.setAlignment(QtCore.Qt.AlignCenter)
        self.winrate_hero_label.setObjectName("winrate_hero_label")
        self.accuracy_hero_text_label = QtWidgets.QLabel(self.heroes_tab)
        self.accuracy_hero_text_label.setGeometry(QtCore.QRect(200, 200, 170, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.accuracy_hero_text_label.setFont(font)
        self.accuracy_hero_text_label.setStyleSheet("color: #9daac8")
        self.accuracy_hero_text_label.setObjectName("accuracy_hero_text_label")
        self.accuracy_hero_label = QtWidgets.QLabel(self.heroes_tab)
        self.accuracy_hero_label.setGeometry(QtCore.QRect(420, 199, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.accuracy_hero_label.setFont(font)
        self.accuracy_hero_label.setStyleSheet("color: white")
        self.accuracy_hero_label.setAlignment(QtCore.Qt.AlignCenter)
        self.accuracy_hero_label.setObjectName("accuracy_hero_label")
        self.critical_accuracy_hero_text_label = QtWidgets.QLabel(self.heroes_tab)
        self.critical_accuracy_hero_text_label.setGeometry(QtCore.QRect(518, 196, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.critical_accuracy_hero_text_label.setFont(font)
        self.critical_accuracy_hero_text_label.setStyleSheet("color: #9daac8")
        self.critical_accuracy_hero_text_label.setObjectName("critical_accuracy_hero_text_label")
        self.critical_accuracy_hero_label = QtWidgets.QLabel(self.heroes_tab)
        self.critical_accuracy_hero_label.setGeometry(QtCore.QRect(714, 196, 80, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.critical_accuracy_hero_label.setFont(font)
        self.critical_accuracy_hero_label.setStyleSheet("color: white")
        self.critical_accuracy_hero_label.setAlignment(QtCore.Qt.AlignCenter)
        self.critical_accuracy_hero_label.setObjectName("critical_accuracy_hero_label")
        self.final_blows_hero_text_label = QtWidgets.QLabel(self.heroes_tab)
        self.final_blows_hero_text_label.setGeometry(QtCore.QRect(519, 160, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.final_blows_hero_text_label.setFont(font)
        self.final_blows_hero_text_label.setStyleSheet("color: #9daac8")
        self.final_blows_hero_text_label.setObjectName("final_blows_hero_text_label")
        self.final_blows_hero_label = QtWidgets.QLabel(self.heroes_tab)
        self.final_blows_hero_label.setGeometry(QtCore.QRect(723, 160, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.final_blows_hero_label.setFont(font)
        self.final_blows_hero_label.setStyleSheet("color: white")
        self.final_blows_hero_label.setAlignment(QtCore.Qt.AlignCenter)
        self.final_blows_hero_label.setObjectName("final_blows_hero_label")
        self.avg_solo_elims_hero_text_label = QtWidgets.QLabel(self.heroes_tab)
        self.avg_solo_elims_hero_text_label.setGeometry(QtCore.QRect(201, 232, 130, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.avg_solo_elims_hero_text_label.setFont(font)
        self.avg_solo_elims_hero_text_label.setStyleSheet("color: #9daac8")
        self.avg_solo_elims_hero_text_label.setObjectName("avg_solo_elims_hero_text_label")
        self.avg_solo_elims_hero_label = QtWidgets.QLabel(self.heroes_tab)
        self.avg_solo_elims_hero_label.setGeometry(QtCore.QRect(430, 232, 50, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.avg_solo_elims_hero_label.setFont(font)
        self.avg_solo_elims_hero_label.setStyleSheet("color: white")
        self.avg_solo_elims_hero_label.setAlignment(QtCore.Qt.AlignCenter)
        self.avg_solo_elims_hero_label.setObjectName("avg_solo_elims_hero_label")
        self.avatar_hero_label = QtWidgets.QLabel(self.heroes_tab)
        self.avatar_hero_label.setGeometry(QtCore.QRect(430, 380, 170, 140))
        self.avatar_hero_label.setText("")
        self.avatar_hero_label.setObjectName("avatar_hero_label")
        self.choose_hero_stats_listWidget = QtWidgets.QListWidget(self.heroes_tab)
        self.choose_hero_stats_listWidget.setGeometry(QtCore.QRect(0, 0, 191, 551))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.choose_hero_stats_listWidget.setFont(font)
        self.choose_hero_stats_listWidget.setStyleSheet("color: white; background-color: #2d3856 ")
        self.choose_hero_stats_listWidget.setObjectName("choose_hero_stats_listWidget")
        self.avg_fire_time_hero_text_label = QtWidgets.QLabel(self.heroes_tab)
        self.avg_fire_time_hero_text_label.setGeometry(QtCore.QRect(202, 274, 130, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.avg_fire_time_hero_text_label.setFont(font)
        self.avg_fire_time_hero_text_label.setStyleSheet("color: #9daac8")
        self.avg_fire_time_hero_text_label.setObjectName("avg_fire_time_hero_text_label")
        self.avg_obj_time_hero_label = QtWidgets.QLabel(self.heroes_tab)
        self.avg_obj_time_hero_label.setGeometry(QtCore.QRect(723, 242, 60, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.avg_obj_time_hero_label.setFont(font)
        self.avg_obj_time_hero_label.setStyleSheet("color: white")
        self.avg_obj_time_hero_label.setAlignment(QtCore.Qt.AlignCenter)
        self.avg_obj_time_hero_label.setObjectName("avg_obj_time_hero_label")
        self.avg_fire_time_hero_label = QtWidgets.QLabel(self.heroes_tab)
        self.avg_fire_time_hero_label.setGeometry(QtCore.QRect(400, 275, 110, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.avg_fire_time_hero_label.setFont(font)
        self.avg_fire_time_hero_label.setStyleSheet("color: white")
        self.avg_fire_time_hero_label.setAlignment(QtCore.Qt.AlignCenter)
        self.avg_fire_time_hero_label.setObjectName("avg_fire_time_hero_label")
        self.avg_obj_time_hero_text_label = QtWidgets.QLabel(self.heroes_tab)
        self.avg_obj_time_hero_text_label.setGeometry(QtCore.QRect(517, 242, 210, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.avg_obj_time_hero_text_label.setFont(font)
        self.avg_obj_time_hero_text_label.setStyleSheet("color: #9daac8")
        self.avg_obj_time_hero_text_label.setObjectName("avg_obj_time_hero_text_label")
        self.games_hero_text_label = QtWidgets.QLabel(self.heroes_tab)
        self.games_hero_text_label.setGeometry(QtCore.QRect(200, 330, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.games_hero_text_label.setFont(font)
        self.games_hero_text_label.setStyleSheet("color: #9daac8")
        self.games_hero_text_label.setObjectName("games_hero_text_label")
        self.games_won_hero_label = QtWidgets.QLabel(self.heroes_tab)
        self.games_won_hero_label.setGeometry(QtCore.QRect(310, 330, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.games_won_hero_label.setFont(font)
        self.games_won_hero_label.setStyleSheet("color: #77f968")
        self.games_won_hero_label.setObjectName("games_won_hero_label")
        self.games_lost_hero_label = QtWidgets.QLabel(self.heroes_tab)
        self.games_lost_hero_label.setGeometry(QtCore.QRect(396, 330, 64, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.games_lost_hero_label.setFont(font)
        self.games_lost_hero_label.setStyleSheet("color: red")
        self.games_lost_hero_label.setObjectName("games_lost_hero_label")
        self.games_tied_hero_label = QtWidgets.QLabel(self.heroes_tab)
        self.games_tied_hero_label.setGeometry(QtCore.QRect(480, 330, 64, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.games_tied_hero_label.setFont(font)
        self.games_tied_hero_label.setStyleSheet("color: grey")
        self.games_tied_hero_label.setObjectName("games_tied_hero_label")
        self.slash_label = QtWidgets.QLabel(self.heroes_tab)
        self.slash_label.setGeometry(QtCore.QRect(370, 330, 20, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.slash_label.setFont(font)
        self.slash_label.setStyleSheet("color: #9daac8")
        self.slash_label.setAlignment(QtCore.Qt.AlignCenter)
        self.slash_label.setObjectName("slash_label")
        self.slash_label_2 = QtWidgets.QLabel(self.heroes_tab)
        self.slash_label_2.setGeometry(QtCore.QRect(460, 330, 20, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.slash_label_2.setFont(font)
        self.slash_label_2.setStyleSheet("color: #9daac8")
        self.slash_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.slash_label_2.setObjectName("slash_label_2")
        self.tabWidget.addTab(self.heroes_tab, "")
        self.settings_tab = QtWidgets.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.add_profile_button = QtWidgets.QPushButton(self.settings_tab)
        self.add_profile_button.setGeometry(QtCore.QRect(660, 20, 131, 28))
        self.add_profile_button.setStyleSheet("color: white; background-color: grey")
        self.add_profile_button.setObjectName("add_profile_button")
        self.add_profile_nickname_lineEdit = QtWidgets.QLineEdit(self.settings_tab)
        self.add_profile_nickname_lineEdit.setGeometry(QtCore.QRect(382, 18, 140, 30))
        self.add_profile_nickname_lineEdit.setStyleSheet("color: white; background-color: #2d3856 ")
        self.add_profile_nickname_lineEdit.setText("")
        self.add_profile_nickname_lineEdit.setObjectName("add_profile_nickname_lineEdit")
        self.split_label = QtWidgets.QLabel(self.settings_tab)
        self.split_label.setGeometry(QtCore.QRect(527, 18, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.split_label.setFont(font)
        self.split_label.setStyleSheet("color: #9daac8")
        self.split_label.setObjectName("split_label")
        self.add_profile_number_lineEdit = QtWidgets.QLineEdit(self.settings_tab)
        self.add_profile_number_lineEdit.setGeometry(QtCore.QRect(552, 18, 91, 30))
        self.add_profile_number_lineEdit.setStyleSheet("color: white; background-color: #2d3856 ")
        self.add_profile_number_lineEdit.setObjectName("add_profile_number_lineEdit")
        self.label = QtWidgets.QLabel(self.settings_tab)
        self.label.setGeometry(QtCore.QRect(390, 50, 381, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #9daac8")
        self.label.setObjectName("label")
        self.choose_acc_settings_listWidget = QtWidgets.QListWidget(self.settings_tab)
        self.choose_acc_settings_listWidget.setGeometry(QtCore.QRect(5, 10, 370, 200))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.choose_acc_settings_listWidget.setFont(font)
        self.choose_acc_settings_listWidget.setStyleSheet("color: white; background-color: #2d3856 ")
        self.choose_acc_settings_listWidget.setObjectName("choose_acc_settings_listWidget")
        self.eng_lang_button = QtWidgets.QPushButton(self.settings_tab)
        self.eng_lang_button.setGeometry(QtCore.QRect(574, 103, 61, 28))
        self.eng_lang_button.setStyleSheet("color: white; background-color: grey")
        self.eng_lang_button.setObjectName("eng_lang_button")
        self.ru_lang_button = QtWidgets.QPushButton(self.settings_tab)
        self.ru_lang_button.setGeometry(QtCore.QRect(494, 103, 61, 28))
        self.ru_lang_button.setStyleSheet("color: white; background-color: grey")
        self.ru_lang_button.setObjectName("ru_lang_button")
        self.language_text_label = QtWidgets.QLabel(self.settings_tab)
        self.language_text_label.setGeometry(QtCore.QRect(390, 100, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.language_text_label.setFont(font)
        self.language_text_label.setStyleSheet("color: #9daac8")
        self.language_text_label.setAlignment(QtCore.Qt.AlignCenter)
        self.language_text_label.setObjectName("language_text_label")
        self.tabWidget.addTab(self.settings_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.update_information_button.setText(_translate("MainWindow", "Обновить информацию"))
        self.current_rank_text_label.setText(_translate("MainWindow", "Текущий ранг"))
        self.current_rank_label.setText(_translate("MainWindow", "0"))
        self.level_label.setText(_translate("MainWindow", "Уровень"))
        self.current_level_label.setText(_translate("MainWindow", "0"))
        self.battle_tag_label.setText(_translate("MainWindow", "Choose profile"))
        self.reputation_level_label.setText(_translate("MainWindow", "Уровень репутации"))
        self.current_reputation_label.setText(_translate("MainWindow", "0"))
        self.timeinseason_text_label.setText(_translate("MainWindow", "Сыграно часов за сезон"))
        self.current_hours_played_inrank_label.setText(_translate("MainWindow", "0"))
        self.wins_text_label.setText(_translate("MainWindow", "Побед:"))
        self.games_lost_text_label.setText(_translate("MainWindow", "Поражений:"))
        self.games_tied_text_label.setText(_translate("MainWindow", "Ничьих:"))
        self.current_games_won_label.setText(_translate("MainWindow", "0"))
        self.current_games_lost_label.setText(_translate("MainWindow", "0"))
        self.current_games_tied_label.setText(_translate("MainWindow", "0"))
        self.winrate_text_label.setText(_translate("MainWindow", "Винрейт"))
        self.current_winrate_acc_label.setText(_translate("MainWindow", "0%"))
        self.last_activity_label.setText(_translate("MainWindow", "Последняя активность"))
        self.change_games_won_label.setText(_translate("MainWindow", "0"))
        self.games_lost_change_text_label.setText(_translate("MainWindow", "Поражений:"))
        self.wins_change_text_label.setText(_translate("MainWindow", "Побед:"))
        self.games_tied_change_text_label.setText(_translate("MainWindow", "Ничьих:"))
        self.change_games_lost_label.setText(_translate("MainWindow", "0"))
        self.change_games_tied_label.setText(_translate("MainWindow", "0"))
        self.last_rank_change_text_label.setText(_translate("MainWindow", "Ранг:"))
        self.last_change_rank_label.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.profile_tab), _translate("MainWindow", "Профиль"))
        self.most_eliminations_acc_text_lable.setText(_translate("MainWindow", "Убийств"))
        self.total_eliminations_acc_text_lable.setText(_translate("MainWindow", "Всего"))
        self.most_elims_acc_label.setText(_translate("MainWindow", "0"))
        self.total_elims_acc_label.setText(_translate("MainWindow", "0"))
        self.most_final_blows_acc_text_label.setText(_translate("MainWindow", "Добиваний"))
        self.total_final_blows_acc_text_label.setText(_translate("MainWindow", "Всего"))
        self.most_final_blows_acc_label.setText(_translate("MainWindow", "0"))
        self.total_final_blows_acc_label.setText(_translate("MainWindow", "0"))
        self.most_obj_elims_acc_text_label.setText(_translate("MainWindow", "Убийств у объектов"))
        self.total_obj_elims_acc_text_label.setText(_translate("MainWindow", "Всего"))
        self.most_obj_elims_acc_label.setText(_translate("MainWindow", "0"))
        self.total_obj_elims_acc_label.setText(_translate("MainWindow", "0"))
        self.most_obj_time_acc_text_label.setText(_translate("MainWindow", "Выполнение задач"))
        self.total_obj_time_acc_text_label.setText(_translate("MainWindow", "Всего"))
        self.most_obj_time_acc_label.setText(_translate("MainWindow", "0"))
        self.total_obj_time_acc_label.setText(_translate("MainWindow", "0"))
        self.most_heroes_dmg_acc_text_label.setText(_translate("MainWindow", "Урона по героям"))
        self.total_heroes_dmg_acc_text_label.setText(_translate("MainWindow", "Всего"))
        self.most_heroes_dmg_acc_label.setText(_translate("MainWindow", "0"))
        self.total_heroes_dmg_acc_label.setText(_translate("MainWindow", "0"))
        self.most_healing_acc_text_label.setText(_translate("MainWindow", "Лечение"))
        self.total_healing_acc_text_label.setText(_translate("MainWindow", "Всего"))
        self.most_healing_acc_label.setText(_translate("MainWindow", "0"))
        self.total_healing_acc_label.setText(_translate("MainWindow", "0"))
        self.most_fire_time_acc_text_label.setText(_translate("MainWindow", "Время в ударе"))
        self.total_fire_time_acc_text_label.setText(_translate("MainWindow", "Всего"))
        self.most_fire_time_acc_label.setText(_translate("MainWindow", "0"))
        self.total_fire_time_acc_label.setText(_translate("MainWindow", "0"))
        self.most_solo_elims_acc_text_label.setText(_translate("MainWindow", "Одиночных убийств"))
        self.total_solo_elims_acc_text_label.setText(_translate("MainWindow", "Всего"))
        self.most_solo_elims_acc_label.setText(_translate("MainWindow", "0"))
        self.total_solo_elims_acc_label.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.statistic_tab), _translate("MainWindow", "Статистика"))
        self.avg_elims_hero_text_label.setText(_translate("MainWindow", "Убийств"))
        self.avg_elims_hero_label.setText(_translate("MainWindow", "0"))
        self.avg_obj_elims_hero_text_label.setText(_translate("MainWindow", "Убийств у объекта"))
        self.avg_obj_elims_hero_label.setText(_translate("MainWindow", "0"))
        self.avg_damage_done_hero_text_label.setText(_translate("MainWindow", "Урон"))
        self.avg_damage_done_hero_label.setText(_translate("MainWindow", "0"))
        self.abg_deaths_hero_text_label.setText(_translate("MainWindow", "Смертей"))
        self.avg_deaths_hero_label.setText(_translate("MainWindow", "0"))
        self.avg_healing_done_hero_text_label.setText(_translate("MainWindow", "Лечение"))
        self.avg_healing_done_hero_label.setText(_translate("MainWindow", "0"))
        self.time_played_hero_text_label.setText(_translate("MainWindow", "Время в игре"))
        self.time_played_hero_label.setText(_translate("MainWindow", "0"))
        self.winrate_hero_text_label.setText(_translate("MainWindow", "Винрейт"))
        self.winrate_hero_label.setText(_translate("MainWindow", "0"))
        self.accuracy_hero_text_label.setText(_translate("MainWindow", "Меткость"))
        self.accuracy_hero_label.setText(_translate("MainWindow", "0"))
        self.critical_accuracy_hero_text_label.setText(_translate("MainWindow", "Меткость крит"))
        self.critical_accuracy_hero_label.setText(_translate("MainWindow", "0"))
        self.final_blows_hero_text_label.setText(_translate("MainWindow", "Добивания"))
        self.final_blows_hero_label.setText(_translate("MainWindow", "0"))
        self.avg_solo_elims_hero_text_label.setText(_translate("MainWindow", "Соло килы"))
        self.avg_solo_elims_hero_label.setText(_translate("MainWindow", "0"))
        self.avg_fire_time_hero_text_label.setText(_translate("MainWindow", "В ударе"))
        self.avg_obj_time_hero_label.setText(_translate("MainWindow", "0"))
        self.avg_fire_time_hero_label.setText(_translate("MainWindow", "0"))
        self.avg_obj_time_hero_text_label.setText(_translate("MainWindow", "Выполнение задач"))
        self.games_hero_text_label.setText(_translate("MainWindow", "Матчей:"))
        self.games_won_hero_label.setText(_translate("MainWindow", "0"))
        self.games_lost_hero_label.setText(_translate("MainWindow", "0"))
        self.games_tied_hero_label.setText(_translate("MainWindow", "0"))
        self.slash_label.setText(_translate("MainWindow", "/"))
        self.slash_label_2.setText(_translate("MainWindow", "/"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.heroes_tab), _translate("MainWindow", "Герои"))
        self.add_profile_button.setText(_translate("MainWindow", "Добавить профиль"))
        self.add_profile_nickname_lineEdit.setPlaceholderText(_translate("MainWindow", "NICKNAME"))
        self.split_label.setText(_translate("MainWindow", "#"))
        self.add_profile_number_lineEdit.setPlaceholderText(_translate("MainWindow", "12345"))
        self.label.setText(_translate("MainWindow", "Двойной клик по профилю для его удаления"))
        self.eng_lang_button.setText(_translate("MainWindow", "EN"))
        self.ru_lang_button.setText(_translate("MainWindow", "RU"))
        self.language_text_label.setText(_translate("MainWindow", "Language"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings_tab), _translate("MainWindow", "Настройки"))

